---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAD473TKJ6nzUkm7QdC/50DdYgWf8VgrnlGqAWfNkXuG9B4NxrTRRpw39F8+a+/oArNUP0RjizzWuNkVjJTpppJUuKbKmMvISZubfGKTAdRBr42ZEYQ78SWb1Eb0xueRxy9MdOQ9qr0q85ZVhehkIHUqY7npGWbKk36ufq5qbXEuR9b8d2SykqJPYBixZhk0Lm54Ww7gRjlhafDAkMljAyF0NXV+CDYXl13w+aixFsF4Fw4kGsUaWB8xJ9b0olmpnT4Z917Ol4dOEBv9p3piAsb36xCakJHpS/fUD6cKfiNIWtKu+tJqNNuVJOEqRr17ngb41Lnbdkqa8+gzrHbQtFtBEwpa6u2yGCZlW5ZcVXaqekFyD43zUI3RGu3v0/76or2BOQVuO0p4N6zHhBvuQ78/8fX6p+r+iOH3uii9ET0k46gHFMN9oL74/pXGDhOBnPz3wv9VhNd/5Namk+FBBT1R3rG5wxMV0cGCmzERZ7e8TeAtZIe1T2t0bdEQfocHU8qQ4pMPagZUkSIwFSR/8hyT3ubgW5n1YfH2WcYjNEXNEb9BARZ5OxGF7ZXXYAWkeIW4Uz82xmVi0H6n0AjUuHYqkBkbRAm0osUB+K93BlYq5Ioj+7iWyd9LikrdDS9qm7jx8P+zBf1OReAy/Q+fUMC1SRlZwJsQ4PTr4xLDeffGgkmHfeA5oD9iEWlUQUpOL+OLJJYXDu+VbBwxWAfimRlCw==
    GF_SECURITY_ADMIN_USER: AgDOu/4b2hUnxqLjH27vR5JgbBOP3KwWuUhIzCN4IP6z7sbGdjMAS225RhxPhoCMil22TSQDFPbkOsthvf3/7u/W1uJuROr/MSQCa84e17NhvpRWDF42/uV66biqu7kyZ6rqVMToUQ29HHEC1nG3z233uSvSmuoW33l8UpLvxD4LwWXjAMZ0wSCTivhm7cAqSnfJKY9NxODj5wpKAv2q7Ukmsv1scdsWCtMWvccZgtCQGU/nKUxy0e/qsoVEldtsMJIGpughrhOM2YRGJAmG2UDvQK208RSabRieXHhyecHrzkTWBP63T9XiqUvfi6M0Ni6JV6TnKL/Pdzik/XfmMcXr0ydgeSDbWsfO69GWT7o6o9dPs6Rd60Iw+4xjtWm5HMXam7Cg/c12sEbWYsbQchiEC2usr97jhhZ4MIMVhYKyQNsJARyu9ZYNtC0tRs3Cf2PTeCAqECFhfGiRhjx3fqBJKlUBV7BgL7kJMG8xb8/pMVz2FvJUlcwTAV96xoA9SX+EIDxOOS6h6WOBTjQTcaqnwBNgbGp7F8kIGNg25IZpUuiuzLkw8XhL2twVkcy/90gOH7DNDs8Chg0xzvDMDo6rSvYxdLFb2OM5invvqJwfhw4C4VmYy6CXtiE4aQTmU7w13gU5FUeUbOEHBe5B5Qv8gIYuW4x08AoROFxL2VfzvLa0ZoF9Mj7kKNro7omMTfJfGEpRlA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
