---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgDbvzwEaTNR2La/P+sb+vMlbygtLXyV3mmcgY7FdTkZpwijYJRW2pfkN2YK6WrPbCDBwRpjZUKwCeVax4KjTKnGRvK31TCfUsFYoXK2udlcCUOJAXEV8wdcQKBIu3GFmJdZpGgJSWgBkvDk/Qb7oQ80gll9EVqvJ+zdy0zPK2QMI18byL5ES5SvPIAG8FdwewiLSNX0banpQUfStU+Uv00mnqr9IK6AERLdN8ccdXKC8aXKpb9NHcm/9dwi6/ZBoJfgWxNWY3Y/yxNbtKhFH2vZRs/2O2l2uUW1Pg1/AXIdeIaW90nyz2fu8AdEqoNS3oXk9G5rjcbAMa6bp7D8s8SJBcmIxiL3OzpoUnw/YIicDc4ppLvHhOZ6eB4Adz3RE45BpvYTfEzpBY/up0GI5PmFzfeLyh3OEzpObGxGbpqqQRbEgk18qzlDj9K10bQeiqxd+iiIg0pLv8+AbzE5mNMoO8GpbZFGD1xc2IYBB67YLs1zikZu/avDfF+47hP50QJtc2m3SCI0DpuGAa97HSTUG6ZHh5JMFw6J8NiCJdCznA2vKC0OITxszSqW9uiAKtkI5/HlxYsrmlkPyhoF9FT4FMcsKYvqdOg+bERzsFZHR4/yyej1CxNbGeAAwQ/Sv4tntdrKheou8i0u2ZpqgcIQCwFFztPsrWSGYpnDBAbdIbmOcxNXFihrajcbX5I7SuKQrWDLBc4MGpzllNVFWaAFJg==
    GF_SECURITY_ADMIN_USER: AgAzQ99FWinVA8D/h3I6rLXdHn4xyVDXOilDGsxW9rPKi3p5YnQyvJtrjYC5prowDT8riWfQX5iKdZPdy2Ppg1TgHfbwz4pwi2+BM1a9eT5cFsAiKPCQp57T1MKPosn+j2Tq7yzLBTj/IMKGOOq66EKrAu1yzfTLcuWs7mkgtMGNx5mg77Aq2tK3+bsMVfgaHo1ladxjWyFkl3RPT3EbNs7t3CjpqUp0YSrqXedeiWf0RmSkgKsowVgvdX0qgKVmrmc8UilpOxj6L0oaR2+0fvlRJW9RgMaAbuY2KumZCSsD8LLctMx3awIGHC8MxEiK3M7titd1lqt/MuRcbcvyii9A2ob1tT7AniPHZdJaUAZSM0O5C1MISndnkybBnN/MpIXECLbPjzNWm9O9vUKLOurAjDcXWFpNIDUTu1Ps25EgrOzO/GP4pg7DbLR25U87akl5eq7RFtKBcpRFYF+y5zE5iFAseXNnLBPy2cW1n+6b/4vLcaEfBXkVX5ad5acRMObhkwvzOErz00tCKGiwD4fcRZrtuLFrh2nf2h4jDallrTeygm5kiV/adTG+z4BkDd6WHOcHofTXVKItFXJYUranJp1I2uj2sLvR0aHiFHNKqdsyUAfo9kLDTjLT09rreAJ/gwByGas0p63dcnKJINnHnUDgxLocUxHALc3HZwiZBcIGH1BGcfxpB4TAhBwWdKcTn4oIfw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
