---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgDD4NmzuMbrdbqonD81wGpJ3iiYxey6C8lhbEvNaOsQ/F1qT9b/L/k+KjOEiATtBGeECOph4ufELVgh0IC4/Lr39Cio/WFRayXsyF9FoCk8s4jO/MOUDWxS8jnSv8+WYupZUCrG9muJ3mAOC04zmtiNWDCZrFtdWjKorGI2BZ+JAmN+GspKsRDtL760rmlkf57McPJcnOU1ZdIK4SVoo/reHmxzeM/ESzjoSWgC9iQb+W2Zjvv7/APugIwNAY73Z1LBob3bYrZIlfN8HOUxSCfI2G4QVoHMY1EFba2YYs2C5w9WnuUw5kcv+rkCiH3m9kDMUFfnKpNwbPg9aAMdAG/5WSEWzLB5mgAnuZppUeUvLPDfowQJum2NsvuwDPZ0sXhrcHrFW60nVKa0QParfK7FVtPHif925fbFRPb9bYG++IySeAm/F1ZK27JXuK9Xma8+d05SI/CnGzcCiLdGRgVjQXIOidE7ZXViGij9mgtX4NnmsP8vVR21gmxj3BdRiK9lPVn0mXxw2hdCmH9M71dkz2QEf8TmXU8WgPEfNHLpoDYPP5BuS05VrG8ROaBEJz/LajTKp59z/jw2gffLW9xQAEp+vvjgJPEvPmnoryFgKxwqrCIo2u0Nq7vdXyzfHjZIxr0OL0Ov36BfXAiQg9paXLnGRgkUImVxep+yccf+k7opFsRvr0WkvslRY23ObmOt48RrrGcXkOV89lRzH7dzRA==
    GF_SECURITY_ADMIN_USER: AgAKUApP29YDwBzTFj7pYA6PfTV7jVqPGIwPAGf3kqWxEBAKlzYoroAB9IqrmMxzlIWlWT9ZUUt8uaG1B/UAPMRrDtdKHvlDeUOeEMOTbJW1bcWDeZp1Ir0rN0pMozSRdiV7lsvWxSDUmuDYJ5+rWRpjcCgeRrD9eKE4zjtnuLtdXD1Zy2HWWdVoREEgRG3w9oCPYZ5tpGzhaLWYqQ+9GoJtMLiRo2PRXvdehM+rNNII4eX5boFNrUUjjrfb4nXfwno05tK1gCra/3UvztFN/cuKNHt79wqNS1dVU3/S6fnEeJ7T9oZHoqXheYQyKa/xkbXlM5yueXVR2eo0AoN3nu6WzayBoQagBOxevTAbCb23qIM17r7Z0F0uhCt4BjEIORNP4SAiNiiU96UNrH4uTXJt6edg8l95VkWsaj/IFWRF3EsGAoOx1ADHQq6LR3ogDJkZGh5lDZNi2XvVeayRnn6/Ni6SWKHKV8ODADi6r46gXrb5UpsXdG5GdxoFPxJDbgm/DzzPrSr3beeDoHrt3iK6SbD0tGuBAZswlIP+ozcF6P5EasqYBzkb/Vg7iB8hAjeKXesr/bYx93Gmz8A86OzGCWW/rvipQaym/yGiQ9vrkYitcABL2jUhlrsrY6Kbghu4yWvflnyx6uaYpqGrtDAjSkFoc34P5fTYipgriPWPoSAQF5723ucjEwGHTNDllJ6IjbCNOkVn
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
